os: osx
osx_image: xcode10.3
language: objective-c
before_install:
  - brew upgrade >/dev/null
script:
  - brew install fityk.rb
  - brew install pango.rb
  - brew install gnuplot.rb 
  - brew install hdf4.rb
  - brew install hdf5-parallel.rb
  - brew install --head -v gnuplot_multi.rb && brew test gnuplot_multi
  - brew install --head -v smilei.rb
