os: osx
osx_image: xcode10.3
language: objective-c
before_install:
  - brew upgrade >/dev/null
script:
  - brew install -v pango.rb
  - brew install -v gnuplot.rb 
  - brew install -v hdf4.rb
  - brew install -v hdf5-parallel.rb
  - brew install --head -v gnuplot_multi.rb && brew test gnuplot_multi
  - brew install --head -v smilei.rb
  - brew install fityk.rb